### ISSUE TITLE
Conversion from real to complex and the issue with the generator function

### ISSUE THREAD

**Issue by hayatoikoma** [gaika/ArrayFire.jl#10]
In ArrayFire, the conversion from real to complex is supported by `cplx` and `cplx2`. I think `complexes` in `generate.jl` should also include these two functions. Would you add them in `generate.jl`?

I tried to do it by myself, but some errors were returned when I run `generate.jl`. I am not sure if it is because the version of `Clang.jl` is different from what you are using. It would be great if you can add `Clang.jl` in `REQUIRE` to make it runnable. I also wonder if you can make `AF_INCLUDE`, `af_header` and `clang_includes` in `generate.jl` more generic. It would be great if we can call `generator.jl` out-of-the-box.

**Comment by hayatoikoma** [comment]
I also wonder how you want to wrap the ArrayFire functions to match the interface of Julia's built-in functions. In the original repo, they had [`math.jl`](https://github.com/JuliaComputing/ArrayFire.jl/blob/c75d3877a3091e267d115a12e2d59168c1eb7a31/src/math.jl) to wrap functions like `complex`, `real`, `imag`, etc. Where should these wrappers come in this repo?

**Comment by gaika** [comment]
Sorry, generate.jl is very flaky, I could get it working only with a specific version of julia (0.5) and clang.jl (c9c5250071ca5731c7b64610bd5b0c701d5b45de)
