### ISSUE TITLE
complex conversion

### ISSUE THREAD

**Issue by jgbos** [gaika/ArrayFire.jl#26]
Currently the code does not handle `im * X` where, for example `typeof(X)=Array{Complex{Float32}}`. I get the following error

```
MethodError: no method matching af_type(::Type{Complex{Bool}})
Closest candidates are:
  af_type(::Type{Float32}) at .julia/v0.6/ArrayFire/src/util.jl:116
  af_type(::Type{Complex{Float32}}) at .julia/v0.6/ArrayFire/src/util.jl:117
  af_type(::Type{Float64}) at .julia/v0.6/ArrayFire/src/util.jl:118
```

Works fine if I do `1f0im * X`.

Also, `cis.(X)` hangs.

**Comment by gaika** [comment]
fixed `im`, but `cis` and whole bunch of other functions in julia/base/complex.jl are not implemented natively in ArrayFire, if you care enough about them, please create a pull request with tests, I'll add.
