### ISSUE TITLE
Cannot `convert` an object of type Array{Float32,2} to an object of type ArrayFire.AFArray

### ISSUE THREAD

**Issue by mohamed82008** [gaika/ArrayFire.jl#30]
I get this error when I run the following code. Any idea what's wrong?

```
julia> a = rand(Float32, 10, 10);

julia> b = AFArray(a)
ERROR: MethodError: Cannot `convert` an object of type Array{Float32,2} to an object of type ArrayFire.AFArray
This may have arisen from a call to the constructor ArrayFire.AFArray(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] ArrayFire.AFArray(::Array{Float32,2}) at .\sysimg.jl:24
```

**Comment by gaika** [comment]
what version of Julia / ArrayFire.jl are you using? Works fine for v0.5/v0.6 and the latest here. What happens when you Pkg.test("ArrayFire")?

**Comment by mohamed82008** [comment]
Seems like I had to restart Julia, when I did, it precompiled and worked!

**Comment by gaika** [comment]
Have you tried https://github.com/timholy/Revise.jl ? It tracks and reloads file changes in live REPL julia session.

**Comment by mohamed82008** [comment]
Yes I know about it, thanks for suggesting it.
